{% set name = "pygad" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: 9858226f1b1482ab845b3129152fe9ca4457a7bcae5804717647beacd00b734c

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: 20e99eb9f1c5ea1bc35766b628ba2698643f0e04f41d65a62e207b52825dca49
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - cloudpickle

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - ahmedfgad
    - traversaro
