{% set name = "pygad" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: 4291c4e23912684653ed38331f86bd4611715d6068cfaa3363d9039f2fb79259

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: 8906e1e361cd4dd88eda8fefaf7d0fbb5be9fc08b3769d61251596c931cceda7
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - cloudpickle

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - ahmedfgad
    - traversaro
