{% set name = "pygad" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: 9b36d9deeb779f124f39a975d19a02a60c8967d4105a67cc3ec5b3a99ac86e35

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: 1703661793676dc2839969ea934ff8cf396f8ccd63011a530ba8833991aa03eb
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - cloudpickle

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - ahmedfgad
    - traversaro
