{% set name = "pygad" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/pygad/pygad-{{ version }}.tar.gz
    sha256: 89d9f95ee2977bf25c98dec18b1f86cc7788e2edb8c263c2f0386d05a3c25aec

  # This is just used to grab the LICENSE file, missing in the PyPI source archive
  - url: https://github.com/ahmedfgad/GeneticAlgorithmPython/archive/refs/tags/{{ version }}.tar.gz
    sha256: 79b07fac8cfc38e2c9f285c5665d65a455a2f9e145e12f3e7278b31ba6c503ba
    folder: github


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - cloudpickle

test:
  imports:
    - pygad
  commands:
    - pip list --verbose
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ahmedfgad/GeneticAlgorithmPython
  summary: 'PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).'
  license: BSD-3-Clause
  license_file: github/LICENSE


extra:
  recipe-maintainers:
    - ahmedfgad
    - traversaro
